# Generated by Django 3.1.7 on 2021-04-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210406_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='https://soprema.us/wp-content/uploads/2014/12/200x200.gif', upload_to='images/'),
            preserve_default=False,
        ),
    ]
