# Generated by Django 3.1.7 on 2021-04-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='draft',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
