# Generated by Django 3.2.3 on 2021-05-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='draft',
        ),
    ]
